# Generated by Django 6.0.3 on 2026-03-20 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
        ('servicios', '0002_initial'),
        ('usuarios', '0002_alter_usuario_fecha_nacimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['tipo_servicio', 'nombre_servicio']},
        ),
        migrations.AddField(
            model_name='servicio',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion_estimada',
            field=models.PositiveIntegerField(default=30, help_text='Duración en minutos'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('Consulta General', 'Consulta General'), ('Vacunación', 'Vacunación'), ('Esterilización', 'Esterilización'), ('Castración', 'Castración'), ('Cirugía General', 'Cirugía General'), ('Limpieza Dental', 'Limpieza Dental'), ('Baño y Aseo', 'Baño y Aseo'), ('Corte de Pelo', 'Corte de Pelo'), ('Desparasitación', 'Desparasitación'), ('Análisis Clínico', 'Análisis Clínico'), ('Radiografía', 'Radiografía'), ('Ecografía', 'Ecografía'), ('Seguimiento Posadopción', 'Seguimiento Posadopción'), ('Asesoría Comportamiento', 'Asesoría Comportamiento')], default='Consulta General', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='especialista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('idSolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_programada', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('En Progreso', 'En Progreso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('descripcion_problema', models.TextField(blank=True)),
                ('observaciones_especialista', models.TextField(blank=True)),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_solicitados', to='adopcion.mascota')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='servicios.servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_solicitudes_servicio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaDiagnostico',
            fields=[
                ('idRespuesta', models.AutoField(primary_key=True, serialize=False)),
                ('diagnóstico', models.TextField()),
                ('tratamiento_recomendado', models.TextField()),
                ('medicinas_recomendadas', models.TextField(blank=True)),
                ('proxima_cita', models.DateField(blank=True, null=True)),
                ('fecha_diagnostico', models.DateTimeField(auto_now_add=True)),
                ('especialista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos', to='usuarios.especialista')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='servicios.solicitudservicio')),
            ],
        ),
    ]
