# Generated by Django 6.0.3 on 2026-03-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicio_options_servicio_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='foto_servicio',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='numero_solicitantes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicio',
            name='puntuacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
