# Generated by Django 6.0.3 on 2026-03-26 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_servicio_foto_servicio_servicio_numero_solicitantes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestadiagnostico',
            name='especialista',
        ),
    ]
