# Generated by Django 6.0.3 on 2026-03-26 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_remove_respuestadiagnostico_especialista'),
        ('usuarios', '0007_alter_usuario_tipo_administrador_delete_especialista'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestadiagnostico',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos', to='usuarios.administrador'),
        ),
    ]
