# Generated by Django 6.0.2 on 2026-03-13 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Mascota', models.CharField(max_length=100)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Raza', models.CharField(max_length=100)),
                ('Genero', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=6)),
                ('Peso', models.FloatField()),
                ('Especie', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=50)),
                ('Tamaño', models.CharField(max_length=50)),
                ('Historial_Mascota', models.TextField()),
                ('Origen', models.CharField(choices=[('Criador', 'Criador'), ('Refugio', 'Refugio'), ('Rescate', 'Rescate'), ('Abandono', 'Abandono')], default='Criador', max_length=10)),
                ('Tipo_Alimentación', models.CharField(max_length=100)),
                ('Enfermedades', models.TextField()),
                ('Vivienda', models.CharField(max_length=100)),
                ('Vacunas', models.TextField()),
                ('Compatibilidad_Mascota', models.TextField()),
                ('Descripción_Física', models.TextField()),
                ('idCriador', models.IntegerField(blank=True, null=True)),
                ('Estado_Salud', models.CharField(choices=[('Excelente', 'Excelente'), ('Buena', 'Buena'), ('Regular', 'Regular'), ('Mala', 'Mala'), ('Crítica', 'Crítica')], default='Buena', max_length=10)),
                ('Esterilizado', models.BooleanField(default=False)),
                ('Socializado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('idAdopcion', models.AutoField(primary_key=True, serialize=False)),
                ('idPropietario', models.IntegerField()),
                ('idCriador', models.IntegerField(blank=True, null=True)),
                ('Estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], max_length=50)),
                ('Fecha_Solicitud', models.DateField()),
                ('Fecha_Adopción', models.DateField()),
                ('Fecha_Entrega', models.DateField()),
                ('Motivo_Adopción', models.TextField()),
                ('Control_Adopción', models.TextField()),
                ('Estado_Salud_Mascota', models.TextField()),
                ('Lugar_Vivienda', models.TextField()),
                ('Info_Mascota', models.TextField()),
                ('Estado_Ingreso_Mascota', models.TextField()),
                ('Devolución', models.TextField()),
                ('Estado_Solicitud', models.CharField(choices=[('En revisión', 'En revisión'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], max_length=50)),
                ('Fuente_Mascota', models.CharField(choices=[('Criador', 'Criador'), ('Refugio', 'Refugio'), ('Rescate', 'Rescate')], default='Criador', max_length=10)),
                ('idMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.mascota')),
            ],
        ),
    ]
