# Generated by Django 6.0.3 on 2026-03-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='foto_mascota',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='numero_personas_interesadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mascota',
            name='puntuacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
