# Generated by Django 6.0.3 on 2026-03-26 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_mascota_disponible_mascota_fecha_actualizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('idCalificacion', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(choices=[(1, '⭐ 1 - Muy Malo'), (2, '⭐⭐ 2 - Malo'), (3, '⭐⭐⭐ 3 - Regular'), (4, '⭐⭐⭐⭐ 4 - Bueno'), (5, '⭐⭐⭐⭐⭐ 5 - Excelente')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('adopcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='adopcion.adopcion')),
                ('usuario_califica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_calificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'unique_together': {('usuario_califica', 'usuario_calificado', 'adopcion')},
            },
        ),
    ]
