# Generated by Django 6.0.3 on 2026-04-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='Motivo_Rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='Estado_Solicitud',
            field=models.CharField(choices=[('En revisión', 'En revisión'), ('En camino', 'En camino'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], max_length=50),
        ),
    ]
