# Generated by Django 6.0.3 on 2026-04-04 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0006_adopcion_motivo_rechazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='adopcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='adopcion.adopcion'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='enlace_accion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
