# Generated by Django 6.0.3 on 2026-03-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
