# Generated by Django 6.0.3 on 2026-03-20 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_passwordresettoken_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contenido', models.CharField(choices=[('mascota', 'Mascota'), ('servicio', 'Servicio')], max_length=20)),
                ('id_contenido', models.PositiveIntegerField()),
                ('nombre_contenido', models.CharField(max_length=200)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_agregado'],
                'unique_together': {('usuario', 'tipo_contenido', 'id_contenido')},
            },
        ),
    ]
