# Generated by Django 6.0.3 on 2026-03-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='puntuacion_promedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='usuario',
            name='total_calificaciones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
