# Generated by Django 6.0.3 on 2026-03-26 20:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_remove_respuestadiagnostico_especialista'),
        ('usuarios', '0006_usuario_puntuacion_promedio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Propietario', 'Propietario'), ('Criador', 'Criador')], max_length=20),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdministrador', models.AutoField(primary_key=True, serialize=False)),
                ('es_superadmin', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('fecha_ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Especialista',
        ),
    ]
